# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

CRATES="
		ab_glyph@0.2.32
	ab_glyph_rasterizer@0.1.10
	adler2@2.0.1
	aes@0.8.4
	aho-corasick@1.1.4
	aligned-vec@0.6.4
	aligned@0.4.3
	allocator-api2@0.2.21
	android_system_properties@0.1.5
	anstream@1.0.0
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	anyhow@1.0.102
	approx@0.5.1
	arbitrary@1.4.2
	arg_enum_proc_macro@0.3.4
	arrayvec@0.7.6
	as-slice@0.2.1
	ashpd@0.13.11
	async-broadcast@0.7.2
	async-channel@2.5.0
	async-executor@1.14.0
	async-fs@2.2.0
	async-io@2.6.0
	async-lock@3.4.2
	async-process@2.5.0
	async-recursion@1.1.1
	async-signal@0.2.14
	async-task@4.7.1
	async-trait@0.1.89
	atomic-waker@1.1.2
	autocfg@1.5.1
	av-scenechange@0.14.1
	av1-grain@0.2.5
	avif-serialize@0.8.9
	bit_field@0.10.3
	bitflags@2.13.0
	bitstream-io@4.10.0
	block-buffer@0.10.4
	block-padding@0.3.3
	block@0.1.6
	blocking@1.6.2
	built@0.8.1
	bumpalo@3.20.3
	bytemuck@1.25.0
	byteorder-lite@0.1.0
	cairo-rs@0.22.0
	cairo-sys-rs@0.22.0
	cbc@0.1.2
	cc@1.2.64
	cfg-expr@0.20.8
	cfg-if@1.0.4
	chrono@0.4.45
	cipher@0.4.4
	color_quant@1.1.0
	colorchoice@1.0.5
	concurrent-queue@2.5.0
	core-foundation-sys@0.8.7
	cpufeatures@0.2.17
	crc32fast@1.5.0
	crossbeam-deque@0.8.6
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.21
	crunchy@0.2.4
	crypto-common@0.1.7
	digest@0.10.7
	either@1.16.0
	endi@1.1.1
	enumflags2@0.7.12
	enumflags2_derive@0.7.12
	env_filter@1.0.1
	env_logger@0.11.10
	equator-macro@0.4.2
	equator@0.4.2
	equivalent@1.0.2
	errno@0.3.14
	event-listener-strategy@0.5.4
	event-listener@5.4.1
	exr@1.74.0
	fastrand@2.4.1
	fax@0.2.7
	fdeflate@0.3.7
	field-offset@0.3.6
	find-msvc-tools@0.1.9
	flate2@1.1.9
	foldhash@0.1.5
	foldhash@0.2.0
	formatx@0.2.4
	futures-channel@0.3.32
	futures-core@0.3.32
	futures-executor@0.3.32
	futures-io@0.3.32
	futures-lite@2.6.1
	futures-macro@0.3.32
	futures-sink@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	futures@0.3.32
	gdk-pixbuf-sys@0.22.0
	gdk-pixbuf@0.22.0
	gdk4-sys@0.11.2
	gdk4@0.11.2
	generic-array@0.14.7
	getrandom@0.3.4
	getrandom@0.4.2
	gettext-rs@0.7.7
	gettext-sys@0.26.0
	gif@0.14.2
	gio-sys@0.22.0
	gio@0.22.6
	git-version-macro@0.3.9
	git-version@0.3.9
	glam@0.14.0
	glam@0.15.2
	glam@0.16.0
	glam@0.17.3
	glam@0.18.0
	glam@0.19.0
	glam@0.20.5
	glam@0.21.3
	glam@0.22.0
	glam@0.23.0
	glam@0.24.2
	glam@0.25.0
	glam@0.27.0
	glam@0.28.0
	glam@0.29.3
	glam@0.30.10
	glam@0.31.1
	glam@0.32.1
	glib-macros@0.22.6
	glib-sys@0.22.6
	glib@0.22.7
	gobject-sys@0.22.6
	graphene-rs@0.22.0
	graphene-sys@0.22.0
	gsk4-sys@0.11.1
	gsk4@0.11.1
	gtk4-macros@0.11.0
	gtk4-sys@0.11.3
	gtk4@0.11.3
	half@2.7.1
	hashbrown@0.15.5
	hashbrown@0.16.1
	hashbrown@0.17.1
	heck@0.5.0
	hermit-abi@0.5.2
	hex@0.4.3
	hkdf@0.12.4
	hmac@0.12.1
	iana-time-zone-haiku@0.1.2
	iana-time-zone@0.1.65
	id-arena@2.3.0
	image-webp@0.2.4
	image@0.25.10
	imageproc@0.26.2
	imgref@1.12.2
	indexmap@2.14.0
	ink-stroke-modeler-rs@0.1.0
	inout@0.1.4
	interpolate_name@0.2.4
	is_terminal_polyfill@1.70.2
	itertools@0.14.0
	itoa@1.0.18
	jiff-static@0.2.28
	jiff@0.2.28
	jobserver@0.1.34
	js-sys@0.3.102
	lazy_static@1.5.0
	leb128fmt@0.1.0
	lebe@0.5.3
	libadwaita-sys@0.9.1
	libadwaita@0.9.1
	libc@0.2.186
	libfuzzer-sys@0.4.13
	libm@0.2.16
	linux-raw-sys@0.12.1
	locale_config@0.3.0
	log@0.4.32
	loop9@0.1.5
	lru@0.16.4
	malloc_buf@0.0.6
	matrixmultiply@0.3.10
	maybe-rayon@0.1.1
	md-5@0.10.6
	memchr@2.8.2
	memoffset@0.9.1
	miniz_oxide@0.8.9
	moxcms@0.8.1
	nalgebra@0.34.2
	new_debug_unreachable@1.0.6
	no_std_io2@0.9.4
	nom@8.0.0
	noop_proc_macro@0.3.0
	num-bigint-dig@0.9.1
	num-bigint@0.4.6
	num-complex@0.4.6
	num-derive@0.4.2
	num-integer@0.1.46
	num-iter@0.1.45
	num-rational@0.4.2
	num-traits@0.2.19
	num@0.4.3
	objc-foundation@0.1.1
	objc@0.2.7
	objc_id@0.1.1
	once_cell@1.21.4
	once_cell_polyfill@1.70.2
	oo7@0.6.0
	ordered-stream@0.2.0
	owned_ttf_parser@0.25.1
	pango-sys@0.22.0
	pango@0.22.6
	parking@2.2.1
	paste@1.0.15
	pastey@0.1.1
	pbkdf2@0.12.2
	pin-project-lite@0.2.17
	piper@0.2.5
	pkg-config@0.3.33
	png@0.18.1
	polling@3.11.0
	portable-atomic-util@0.2.7
	portable-atomic@1.13.1
	ppv-lite86@0.2.21
	prettyplease@0.2.37
	primal-check@0.3.4
	proc-macro-crate@3.5.0
	proc-macro2@1.0.106
	profiling-procmacros@1.0.18
	profiling@1.0.18
	pxfm@0.1.29
	qoi@0.4.1
	quick-error@2.0.1
	quote@1.0.45
	r-efi@5.3.0
	r-efi@6.0.0
	rand@0.9.4
	rand_chacha@0.9.0
	rand_core@0.9.5
	rand_distr@0.5.1
	rav1e@0.8.1
	ravif@0.13.0
	rawpointer@0.2.1
	rayon-core@1.13.0
	rayon@1.12.0
	regex-automata@0.4.14
	regex-syntax@0.8.11
	regex@1.12.4
	rgb@0.8.53
	rustc_version@0.4.1
	rustdct@0.7.1
	rustfft@6.4.1
	rustix@1.1.4
	rustversion@1.0.22
	safe_arch@0.7.4
	semver@1.0.28
	serde@1.0.228
	serde_bytes@0.11.19
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.150
	serde_repr@0.1.20
	serde_spanned@1.1.1
	sha2@0.10.9
	shell-words@1.1.1
	shlex@2.0.1
	signal-hook-registry@1.4.8
	simba@0.9.1
	simd-adler32@0.3.9
	simd_helpers@0.1.0
	slab@0.4.12
	smallvec@1.15.2
	stable_deref_trait@1.2.1
	strength_reduce@0.2.4
	subtle@2.6.1
	syn@2.0.117
	system-deps@7.0.8
	target-lexicon@0.13.5
	temp-dir@0.1.16
	tempfile@3.27.0
	thiserror-impl@2.0.18
	thiserror@2.0.18
	tiff@0.11.3
	toml@1.1.2+spec-1.1.0
	toml_datetime@1.1.1+spec-1.1.0
	toml_edit@0.25.12+spec-1.1.0
	toml_parser@1.1.2+spec-1.1.0
	toml_writer@1.1.1+spec-1.1.0
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing@0.1.44
	transpose@0.2.3
	ttf-parser@0.25.1
	typenum@1.20.1
	uds_windows@1.2.1
	unicode-ident@1.0.24
	unicode-xid@0.2.6
	utf8parse@0.2.2
	uuid@1.23.3
	v_frame@0.3.9
	version-compare@0.2.1
	version_check@0.9.5
	wasip2@1.0.4+wasi-0.2.12
	wasip3@0.4.0+wasi-0.3.0-rc-2026-01-06
	wasm-bindgen-macro-support@0.2.125
	wasm-bindgen-macro@0.2.125
	wasm-bindgen-shared@0.2.125
	wasm-bindgen@0.2.125
	wasm-encoder@0.244.0
	wasm-metadata@0.244.0
	wasmparser@0.244.0
	weezl@0.1.12
	wide@0.7.33
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-core@0.62.2
	windows-implement@0.60.2
	windows-interface@0.59.3
	windows-link@0.2.1
	windows-result@0.4.1
	windows-strings@0.5.1
	windows-sys@0.61.2
	winnow@1.0.3
	wit-bindgen-core@0.51.0
	wit-bindgen-rust-macro@0.51.0
	wit-bindgen-rust@0.51.0
	wit-bindgen@0.51.0
	wit-bindgen@0.57.1
	wit-component@0.244.0
	wit-parser@0.244.0
	y4m@0.8.0
	zbus@5.16.0
	zbus_macros@5.16.0
	zbus_names@4.3.2
	zerocopy-derive@0.8.52
	zerocopy@0.8.52
	zeroize@1.9.0
	zeroize_derive@1.5.0
	zmij@1.0.21
	zune-core@0.5.1
	zune-inflate@0.2.54
	zune-jpeg@0.5.15
	zvariant@5.12.0
	zvariant_derive@5.12.0
	zvariant_utils@3.4.0
"

RUST_MIN_VER="1.85.0"

inherit cargo gnome.org gnome2 meson xdg

DESCRIPTION="A document viewer for the GNOME desktop"
HOMEPAGE="https://apps.gnome.org/Papers"

# SRC_URI is set by gnome.org eclass.
SRC_URI+=" ${CARGO_CRATE_URIS}"

LICENSE="GPL-2+ MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 BSD MIT Unicode-3.0
	ZLIB
"

# subslot = ppsd4.0.(suffix of libppsdocument-4.0)-ppsv4.0.(suffix of libppsview-4.0)
SLOT="0/ppsd4.0.6-ppsv4.0.5"

KEYWORDS="amd64 ~arm64 ~ppc64 ~riscv ~x86"

IUSE="+comics djvu doc gnome-keyring introspection nautilus +spell sysprof test tiff"
REQUIRED_USE="doc? ( introspection )"

RESTRICT="!test? ( test )"

BDEPEND="
	virtual/pkgconfig
	>=dev-build/meson-1.8.0
	dev-util/blueprint-compiler
	dev-libs/appstream
	dev-libs/appstream-glib
	doc? ( dev-util/gi-docgen )
"

# sys-crates in pycargoebuild order
DEPEND="
	x11-libs/cairo
	x11-libs/gdk-pixbuf[introspection?]
	sys-devel/gettext
	media-libs/graphene
	media-libs/libraw
	x11-libs/pango[introspection?]
"
# meson.build file
DEPEND+="
	>=dev-libs/glib-2.75.0:2
	>=gui-libs/gtk-4.17.1:4
	>=gui-libs/libadwaita-1.8_alpha:1
	media-libs/exempi:2
	>=x11-libs/cairo-1.14.0
	virtual/zlib:=

	sysprof? ( dev-util/sysprof-capture:4 )

	nautilus? ( >=gnome-base/nautilus-43 )
	introspection? ( >=dev-libs/gobject-introspection-1.82.0-r2 )
	spell? ( >=app-text/libspelling-0.2 )
	comics? ( >=app-arch/libarchive-3.6.0 )
	djvu? ( >=app-text/djvu-3.5.22 )

	>=app-text/poppler-25.07.0[cairo]
	x11-libs/cairo

	tiff? ( >=media-libs/tiff-4 )

"
RDEPEND="${DEPEND}
	gnome-keyring? ( app-crypt/libsecret )
"

QA_FLAGS_IGNORED="usr/bin/papers usr/bin/papers-thumbnailer"

src_configure() {
	local emesonargs=(
		$(meson_feature sysprof)
		$(meson_use nautilus)
		$(meson_feature comics)
		$(meson_feature djvu)
		-Dpdf=enabled
		$(meson_feature tiff)
		$(meson_use test tests)
		$(meson_use doc documentation)
		$(meson_use doc user_doc)
		$(meson_feature introspection)
		$(meson_feature sysprof)
		$(meson_feature gnome-keyring keyring)
		$(meson_feature spell spell_check)
	)
	meson_src_configure
	ln -s "${CARGO_HOME}" "${BUILD_DIR}/cargo-home" || die
}

src_install() {
	meson_src_install
	if use doc; then
		mv "${ED}"/usr/share/doc/{libpps*,${PF}/.} || die
	fi
}

pkg_postinst() {
	xdg_pkg_postinst
	gnome2_schemas_update
}

pkg_postrm() {
	xdg_pkg_postrm
	gnome2_schemas_update
}
