x11-wm/mutter:50
app-text/yelp-tools:50
app-editors/gnome-text-editor:50
dev-libs/gjs:1.88
app-crypt/seahorse:50
gnome-extra/zenity:50
gnome-base/nautilus:50
app-arch/gnome-autoar:0.4
net-libs/gnome-online-accounts:50
gnome-base/gnome-desktop:50
media-sound/gnome-sound-recorder:50
games-puzzle/gnome-sudoku:50
dev-libs/libsigc++:3.6
media-gfx/gnome-font-viewer:50
media-gfx/gnome-screenshot:50
dev-libs/gobject-introspection:1.86
dev-lang/vala:0.56
app-accessibility/at-spi2-core:2.59
app-accessibility/orca:50
app-arch/file-roller:50
app-crypt/libsecret:0.21
app-editors/ghex:50
app-text/evince:50
dev-cpp/atkmm:2.28
dev-cpp/glibmm:2.86
dev-cpp/gtkmm:4.21
dev-cpp/pangomm:2.56
dev-libs/glib:2.86
dev-python/pygobject:3.54
gnome-base/dconf:0.40
gnome-base/dconf-editor:50
gnome-base/gdm:50
gnome-base/gnome-common:50
gnome-base/gnome-control-center:50
gnome-base/gnome-keyring:50
gnome-base/gnome-session:50
gnome-base/gnome-settings-daemon:50
gnome-base/gnome-shell:50
gnome-base/gsettings-desktop-schemas:50
gnome-base/gvfs:1.58
gnome-base/libgtop:2.41
gnome-base/librsvg:2.61
gnome-extra/evolution-data-server:50
gnome-extra/evolution-ews:50
dev-util/gnome-builder:50
gnome-extra/gnome-calculator:50
gnome-extra/gnome-calendar:50
gnome-extra/gnome-characters:50
gnome-extra/gnome-clocks:50
gnome-extra/gnome-logs:50
gnome-extra/gnome-shell-extensions:50
gnome-extra/gnome-system-monitor:50
gnome-extra/gnome-user-docs:50
gnome-extra/gnome-weather:50
gnome-extra/sushi:50
gnome-extra/yelp:50
gnome-extra/yelp-xsl:50
mail-client/evolution:50
media-gfx/eog:50
media-gfx/eog-plugins:50
media-sound/gnome-music:50
net-libs/glib-networking:2.80
net-libs/libsoup:3.6
net-misc/rygel
net-wireless/gnome-bluetooth:50
sys-apps/baobab:50
sys-apps/gnome-disk-utility:50
www-client/epiphany:50
x11-libs/gdk-pixbuf:2.44
gui-libs/gtk:4.21
x11-libs/pango:1.58
gui-libs/vte:0.84
gui-libs/libadwaita:1.10
x11-themes/adwaita-icon-theme:50
x11-themes/gnome-backgrounds:50
gnome-extra/gnome-contacts:50
dev-libs/json-glib:1.10
dev-libs/libdazzle:50
dev-libs/template-glib:50
dev-libs/jsonrpc-glib:50
gui-apps/gnome-console:50
sys-apps/xdg-desktop-portal-gnome:50
gui-libs/libpanel
