x11-wm/mutter:51
app-text/yelp-tools:51
app-editors/gnome-text-editor:51
dev-libs/gjs:1.90
app-crypt/seahorse:51
gnome-extra/zenity:51
gnome-base/nautilus:51
app-arch/gnome-autoar:0.5
net-libs/gnome-online-accounts:51
gnome-base/gnome-desktop:51
media-sound/gnome-sound-recorder:51
games-puzzle/gnome-sudoku:51
dev-libs/libsigc++:3.6
media-gfx/gnome-font-viewer:51
media-gfx/gnome-screenshot:51
dev-libs/gobject-introspection:1.86
dev-lang/vala:0.56
app-accessibility/at-spi2-core:2.62
app-accessibility/orca:51
app-arch/file-roller:51
app-crypt/libsecret:0.21
app-editors/ghex:51
app-text/evince:51
dev-cpp/atkmm:2.28
dev-cpp/glibmm:2.86
dev-cpp/gtkmm:4.24
dev-cpp/pangomm:2.56
dev-libs/glib:2.90
dev-python/pygobject:3.58
gnome-base/dconf:52
gnome-base/dconf-editor:51
gnome-base/gdm:51
gnome-base/gnome-common:51
gnome-base/gnome-control-center:51
gnome-base/gnome-keyring:51
gnome-base/gnome-session:51
gnome-base/gnome-settings-daemon:51
gnome-base/gnome-shell:51
gnome-base/gsettings-desktop-schemas:51
gnome-base/gvfs:1.62
gnome-base/libgtop:2.41
gnome-base/librsvg:2.61
gnome-extra/evolution-data-server:51
gnome-extra/evolution-ews:51
dev-util/gnome-builder:51
gnome-extra/gnome-calculator:51
gnome-extra/gnome-calendar:51
gnome-extra/gnome-characters:51
gnome-extra/gnome-clocks:51
gnome-extra/gnome-logs:51
gnome-extra/gnome-shell-extensions:51
gnome-extra/gnome-system-monitor:51
gnome-extra/gnome-user-docs:51
gnome-extra/gnome-weather:51
gnome-extra/sushi:51
gnome-extra/yelp:51
gnome-extra/yelp-xsl:51
mail-client/evolution:51
media-gfx/eog:51
media-gfx/eog-plugins:51
media-sound/gnome-music:51
net-libs/glib-networking:2.80
net-libs/libsoup:3.6
net-misc/rygel
net-wireless/gnome-bluetooth:51
sys-apps/baobab:51
sys-apps/gnome-disk-utility:51
www-client/epiphany:51
x11-libs/gdk-pixbuf:2.44
gui-libs/gtk:4.24
x11-libs/pango:1.58
gui-libs/vte:0.84
gui-libs/libadwaita:1.10
x11-themes/adwaita-icon-theme:51
x11-themes/gnome-backgrounds:51
gnome-extra/gnome-contacts:51
dev-libs/json-glib:1.10
dev-libs/libdazzle:51
dev-libs/template-glib:51
dev-libs/jsonrpc-glib:51
gui-apps/gnome-console:51
sys-apps/xdg-desktop-portal-gnome:51
gui-libs/libpanel
